### ISSUE TITLE
python no module named cv2 on windows 10 

### ISSUE THREAD

**Issue by masspern** [bpurinton/PebbleCounts#12]
``Hi,

just followed instuctions on manual, installed miniconda3 and everything is fine.

Then, as I run

`python PebbleCounts.py -im example_data\ortho_resolution_1.2mmPerPix.tif -ortho y`

I get

`(pebblecounts) C:\Users\perna\AppData\Local\miniconda3\envs\pebblecounts>python PebbleCounts.py -im example_data\ortho_resolution_1.2mmPerPix.tif -ortho y
Traceback (most recent call last):
  File "PebbleCounts.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

**Comment by masspern** [comment]
Solved

used 

`pip install opencv-contrib-python==3.2.0.7`

in the desired environment

**Comment by bpurinton** [comment]
Nice work!
